(function () {
  'use strict';

  const ASSET_VERSION = 'v2.9.1';

  const ASSET_MANIFEST = {
    kingIdle: 'assets/images/king/king_idle.png',
    kingRun1: 'assets/images/king/king_run_1.png',
    kingRun2: 'assets/images/king/king_run_2.png',
    kingIdle1: 'assets/images/king/idle/king_idle_1.png',
    kingIdle2: 'assets/images/king/idle/king_idle_2.png',
    kingRunFrame1: 'assets/images/king/run/king_run_1.png',
    kingRunFrame2: 'assets/images/king/run/king_run_2.png',
    kingRunFrame3: 'assets/images/king/run/king_run_3.png',
    kingRunFrame4: 'assets/images/king/run/king_run_4.png',
    kingHurt: 'assets/images/king/king_hurt.png',
    kingDown: 'assets/images/king/king_down.png',
    allyMilitia: 'assets/images/allies/ally_militia.png',
    allyArcher: 'assets/images/allies/ally_archer.png',
    allySpearman: 'assets/images/allies/ally_spearman.png',
    allyEngineer: 'assets/images/allies/ally_engineer.png',
    allyShield: 'assets/images/allies/ally_shield.png',
    allySpear: 'assets/images/allies/ally_spear.png',
    allyMilitiaAttack1: 'assets/images/allies/attack/ally_militia_attack_1.png',
    allyMilitiaAttack2: 'assets/images/allies/attack/ally_militia_attack_2.png',
    allyMilitiaAttack3: 'assets/images/allies/attack/ally_militia_attack_3.png',
    allyMilitiaAttack4: 'assets/images/allies/attack/ally_militia_attack_4.png',
    allyShieldAttack1: 'assets/images/allies/attack/ally_shield_attack_1.png',
    allyShieldAttack2: 'assets/images/allies/attack/ally_shield_attack_2.png',
    allyShieldAttack3: 'assets/images/allies/attack/ally_shield_attack_3.png',
    allyShieldAttack4: 'assets/images/allies/attack/ally_shield_attack_4.png',
    allySpearAttack1: 'assets/images/allies/attack/ally_spear_attack_1.png',
    allySpearAttack2: 'assets/images/allies/attack/ally_spear_attack_2.png',
    allySpearAttack3: 'assets/images/allies/attack/ally_spear_attack_3.png',
    allySpearAttack4: 'assets/images/allies/attack/ally_spear_attack_4.png',
    allyArcherAttack1: 'assets/images/allies/attack/ally_archer_attack_1.png',
    allyArcherAttack2: 'assets/images/allies/attack/ally_archer_attack_2.png',
    allyArcherAttack3: 'assets/images/allies/attack/ally_archer_attack_3.png',
    allyArcherAttack4: 'assets/images/allies/attack/ally_archer_attack_4.png',
    allyEngineerAttack1: 'assets/images/allies/attack/ally_engineer_attack_1.png',
    allyEngineerAttack2: 'assets/images/allies/attack/ally_engineer_attack_2.png',
    allyEngineerAttack3: 'assets/images/allies/attack/ally_engineer_attack_3.png',
    allyEngineerAttack4: 'assets/images/allies/attack/ally_engineer_attack_4.png',
    enemyGrunt: 'assets/images/enemies/enemy_grunt.png',
    enemyRunner: 'assets/images/enemies/enemy_runner.png',
    enemyBrute: 'assets/images/enemies/enemy_brute.png',
    enemyShield: 'assets/images/enemies/enemy_shield.png',
    enemySaboteur: 'assets/images/enemies/enemy_saboteur.png',
    enemyBomber: 'assets/images/enemies/enemy_bomber.png',
    enemyShaman: 'assets/images/enemies/enemy_shaman.png',
    enemySiegeRam: 'assets/images/enemies/enemy_siege_ram.png',
    enemyWarlord: 'assets/images/enemies/enemy_warlord.png',
    enemyOverlord: 'assets/images/enemies/enemy_overlord.png',
    enemyGruntWalk1: 'assets/images/enemies/walk/enemy_grunt_walk_1.png',
    enemyGruntWalk2: 'assets/images/enemies/walk/enemy_grunt_walk_2.png',
    enemyGruntWalk3: 'assets/images/enemies/walk/enemy_grunt_walk_3.png',
    enemyGruntWalk4: 'assets/images/enemies/walk/enemy_grunt_walk_4.png',
    enemyRunnerWalk1: 'assets/images/enemies/walk/enemy_runner_walk_1.png',
    enemyRunnerWalk2: 'assets/images/enemies/walk/enemy_runner_walk_2.png',
    enemyRunnerWalk3: 'assets/images/enemies/walk/enemy_runner_walk_3.png',
    enemyRunnerWalk4: 'assets/images/enemies/walk/enemy_runner_walk_4.png',
    enemyBruteWalk1: 'assets/images/enemies/walk/enemy_brute_walk_1.png',
    enemyBruteWalk2: 'assets/images/enemies/walk/enemy_brute_walk_2.png',
    enemyBruteWalk3: 'assets/images/enemies/walk/enemy_brute_walk_3.png',
    enemyBruteWalk4: 'assets/images/enemies/walk/enemy_brute_walk_4.png',
    enemyShieldWalk1: 'assets/images/enemies/walk/enemy_shield_walk_1.png',
    enemyShieldWalk2: 'assets/images/enemies/walk/enemy_shield_walk_2.png',
    enemyShieldWalk3: 'assets/images/enemies/walk/enemy_shield_walk_3.png',
    enemyShieldWalk4: 'assets/images/enemies/walk/enemy_shield_walk_4.png',
    enemySaboteurWalk1: 'assets/images/enemies/walk/enemy_saboteur_walk_1.png',
    enemySaboteurWalk2: 'assets/images/enemies/walk/enemy_saboteur_walk_2.png',
    enemySaboteurWalk3: 'assets/images/enemies/walk/enemy_saboteur_walk_3.png',
    enemySaboteurWalk4: 'assets/images/enemies/walk/enemy_saboteur_walk_4.png',
    enemyBomberWalk1: 'assets/images/enemies/walk/enemy_bomber_walk_1.png',
    enemyBomberWalk2: 'assets/images/enemies/walk/enemy_bomber_walk_2.png',
    enemyBomberWalk3: 'assets/images/enemies/walk/enemy_bomber_walk_3.png',
    enemyBomberWalk4: 'assets/images/enemies/walk/enemy_bomber_walk_4.png',
    enemyShamanWalk1: 'assets/images/enemies/walk/enemy_shaman_walk_1.png',
    enemyShamanWalk2: 'assets/images/enemies/walk/enemy_shaman_walk_2.png',
    enemyShamanWalk3: 'assets/images/enemies/walk/enemy_shaman_walk_3.png',
    enemyShamanWalk4: 'assets/images/enemies/walk/enemy_shaman_walk_4.png',
    enemySiegeWalk1: 'assets/images/enemies/walk/enemy_siege_walk_1.png',
    enemySiegeWalk2: 'assets/images/enemies/walk/enemy_siege_walk_2.png',
    enemySiegeWalk3: 'assets/images/enemies/walk/enemy_siege_walk_3.png',
    enemySiegeWalk4: 'assets/images/enemies/walk/enemy_siege_walk_4.png',
    enemyWarlordWalk1: 'assets/images/enemies/walk/enemy_warlord_walk_1.png',
    enemyWarlordWalk2: 'assets/images/enemies/walk/enemy_warlord_walk_2.png',
    enemyWarlordWalk3: 'assets/images/enemies/walk/enemy_warlord_walk_3.png',
    enemyWarlordWalk4: 'assets/images/enemies/walk/enemy_warlord_walk_4.png',
    enemyOverlordWalk1: 'assets/images/enemies/walk/enemy_overlord_walk_1.png',
    enemyOverlordWalk2: 'assets/images/enemies/walk/enemy_overlord_walk_2.png',
    enemyOverlordWalk3: 'assets/images/enemies/walk/enemy_overlord_walk_3.png',
    enemyOverlordWalk4: 'assets/images/enemies/walk/enemy_overlord_walk_4.png',
    buildingPalisade: 'assets/images/buildings/building_palisade.png',
    buildingStoneWall: 'assets/images/buildings/building_stone_wall.png',
    buildingArcherTower: 'assets/images/buildings/building_archer_tower.png',
    buildingCannon: 'assets/images/buildings/building_cannon.png',
    buildingBarracks: 'assets/images/buildings/building_barracks.png',
    buildingGoldMine: 'assets/images/buildings/building_gold_mine.png',
    buildingRepairHut: 'assets/images/buildings/building_repair_hut.png',
    buildingSignalBeacon: 'assets/images/buildings/building_signal_beacon.png',
    buildingWarBanner: 'assets/images/buildings/building_war_banner.png',
    buildingOutpost: 'assets/images/buildings/building_outpost.png',
    buildingMarket: 'assets/images/buildings/building_market.png',
    buildingVillage: 'assets/images/buildings/building_village.png',
    buildingRoyalKeep: 'assets/images/buildings/building_royal_keep.png',
    buildingSpikeTrap: 'assets/images/buildings/building_spike_trap.png',
    tileGrass: 'assets/images/terrain/tile_grass.png',
    tileDirt: 'assets/images/terrain/tile_dirt.png',
    tileRoad: 'assets/images/terrain/tile_road.png',
    tileRiver: 'assets/images/terrain/tile_river.png',
    tileBridge: 'assets/images/terrain/tile_bridge.png',
    tileRock: 'assets/images/terrain/tile_rock.png',
    tileMountain: 'assets/images/terrain/tile_mountain.png',
    tileBuildEmpty: 'assets/images/build_tiles/tile_build_empty.png',
    tileBuildInvesting: 'assets/images/build_tiles/tile_build_investing.png',
    tileBuildActive: 'assets/images/build_tiles/tile_build_active.png',
    tileBuildComplete: 'assets/images/build_tiles/tile_build_complete.png',
    tileBuildLocked: 'assets/images/build_tiles/tile_build_locked.png',
    uiCoin: 'assets/images/ui/ui_coin.png',
    uiHeart: 'assets/images/ui/ui_heart.png',
    uiCastleHp: 'assets/images/ui/ui_castle_hp.png',
    uiPopulation: 'assets/images/ui/ui_population.png',
    uiTerritory: 'assets/images/ui/ui_territory.png',
    uiWave: 'assets/images/ui/ui_wave.png',
    uiWarning: 'assets/images/ui/ui_warning.png',
    uiCrown: 'assets/images/ui/ui_crown.png',
    uiBuild: 'assets/images/ui/ui_build.png',
    uiUpgrade: 'assets/images/ui/ui_upgrade.png',
    fxHit: 'assets/images/effects/fx_hit.png',
    fxExplosion: 'assets/images/effects/fx_explosion.png',
    fxBuild: 'assets/images/effects/fx_build.png',
    fxHeal: 'assets/images/effects/fx_heal.png',
    fxCoinPickup: 'assets/images/effects/fx_coin_pickup.png',
    fxUpgrade: 'assets/images/effects/fx_upgrade.png',
    fxWarning: 'assets/images/effects/fx_warning.png',

    buildingPalisadeThorns: 'assets/images/buildings/upgrades/building_palisade_thorns.png',
    buildingPalisadeReinforced: 'assets/images/buildings/upgrades/building_palisade_reinforced.png',
    buildingStoneWallBastion: 'assets/images/buildings/upgrades/building_stone_wall_bastion.png',
    buildingStoneWallGate: 'assets/images/buildings/upgrades/building_stone_wall_gate.png',
    buildingArcherTowerLongbow: 'assets/images/buildings/upgrades/building_archer_tower_longbow.png',
    buildingArcherTowerRapid: 'assets/images/buildings/upgrades/building_archer_tower_rapid.png',
    buildingCannonHeavy: 'assets/images/buildings/upgrades/building_cannon_heavy.png',
    buildingCannonScatter: 'assets/images/buildings/upgrades/building_cannon_scatter.png',
    buildingBarracksShield: 'assets/images/buildings/upgrades/building_barracks_shield.png',
    buildingBarracksSpear: 'assets/images/buildings/upgrades/building_barracks_spear.png',
    buildingGoldMineTax: 'assets/images/buildings/upgrades/building_gold_mine_tax.png',
    buildingGoldMineVault: 'assets/images/buildings/upgrades/building_gold_mine_vault.png',
    buildingRepairHutFieldwork: 'assets/images/buildings/upgrades/building_repair_hut_fieldwork.png',
    buildingRepairHutWorkshop: 'assets/images/buildings/upgrades/building_repair_hut_workshop.png',
    buildingSpikeTrapBarbed: 'assets/images/buildings/upgrades/building_spike_trap_barbed.png',
    buildingSpikeTrapFrost: 'assets/images/buildings/upgrades/building_spike_trap_frost.png',
    buildingWarBannerMorale: 'assets/images/buildings/upgrades/building_war_banner_morale.png',
    buildingWarBannerCommand: 'assets/images/buildings/upgrades/building_war_banner_command.png',
    buildingSignalBeaconScout: 'assets/images/buildings/upgrades/building_signal_beacon_scout.png',
    buildingSignalBeaconRally: 'assets/images/buildings/upgrades/building_signal_beacon_rally.png',
    buildingVillageLv2: 'assets/images/buildings/upgrades/building_village_lv2.png',
    buildingMarketLv2: 'assets/images/buildings/upgrades/building_market_lv2.png',
    buildingOutpostLv2: 'assets/images/buildings/upgrades/building_outpost_lv2.png',
    buildingTrainingYard: 'assets/images/buildings/upgrades/building_training_yard.png',
    buildingRoyalKeepLv2: 'assets/images/buildings/upgrades/building_royal_keep_lv2.png',
    tileGrassMeadow: 'assets/images/terrain/stage/tile_grass_meadow.png',
    tileRoadMeadow: 'assets/images/terrain/stage/tile_road_meadow.png',
    tileDirtMeadow: 'assets/images/terrain/stage/tile_dirt_meadow.png',
    tileGrassRiver: 'assets/images/terrain/stage/tile_grass_river.png',
    tileRoadRiver: 'assets/images/terrain/stage/tile_road_river.png',
    tileDirtRiver: 'assets/images/terrain/stage/tile_dirt_river.png',
    tileGrassPass: 'assets/images/terrain/stage/tile_grass_pass.png',
    tileRoadPass: 'assets/images/terrain/stage/tile_road_pass.png',
    tileDirtPass: 'assets/images/terrain/stage/tile_dirt_pass.png',
    fxHit1: 'assets/images/effects/frames/fx_hit_1.png',
    fxHit2: 'assets/images/effects/frames/fx_hit_2.png',
    fxHit3: 'assets/images/effects/frames/fx_hit_3.png',
    fxExplosion1: 'assets/images/effects/frames/fx_explosion_1.png',
    fxExplosion2: 'assets/images/effects/frames/fx_explosion_2.png',
    fxExplosion3: 'assets/images/effects/frames/fx_explosion_3.png',
    fxBuild1: 'assets/images/effects/frames/fx_build_1.png',
    fxBuild2: 'assets/images/effects/frames/fx_build_2.png',
    fxBuild3: 'assets/images/effects/frames/fx_build_3.png',
    fxHeal1: 'assets/images/effects/frames/fx_heal_1.png',
    fxHeal2: 'assets/images/effects/frames/fx_heal_2.png',
    fxHeal3: 'assets/images/effects/frames/fx_heal_3.png',
    fxCoinPickup1: 'assets/images/effects/frames/fx_coin_pickup_1.png',
    fxCoinPickup2: 'assets/images/effects/frames/fx_coin_pickup_2.png',
    fxCoinPickup3: 'assets/images/effects/frames/fx_coin_pickup_3.png',
    fxUpgrade1: 'assets/images/effects/frames/fx_upgrade_1.png',
    fxUpgrade2: 'assets/images/effects/frames/fx_upgrade_2.png',
    fxUpgrade3: 'assets/images/effects/frames/fx_upgrade_3.png',
    fxWarning1: 'assets/images/effects/frames/fx_warning_1.png',
    fxWarning2: 'assets/images/effects/frames/fx_warning_2.png',
    fxWarning3: 'assets/images/effects/frames/fx_warning_3.png'
  };

  function versionedAssetSrc(src) {
    if (!src || src.includes('?')) return src;
    return `${src}?asset=${ASSET_VERSION}`;
  }

  function loadGameImages() {
    const images = {};
    for (const [key, src] of Object.entries(ASSET_MANIFEST)) {
      const img = new Image();
      img.src = versionedAssetSrc(src);
      images[key] = img;
    }
    return images;
  }

  window.KBD_ASSET_VERSION = ASSET_VERSION;
  window.KBD_ASSET_MANIFEST = ASSET_MANIFEST;
  window.KBD_LOAD_IMAGES = loadGameImages;
})();
